swagger: "2.0"
info:
  version: 1.0.0
  title: "Esame SE2"
  description: Una Api per controllare lo stato di un astronauta in una stazione spaziale
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-francescoloda.herokuapp.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   /display:
    get:
      description: ritorna tutti gli astronauti
      operationId: GetAstronauti
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronauta'
        default:
          description: Errore
   /displayid/{astroId}:
    get:
      description: cerca un astronauta dato l'id
      operationId: searchAstronauta
      parameters:
        - name: astroId
          in: path
          description: ID dell'astronauta da cercare
          required: true
          type: string
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronauta'
        default:
          description: Errore
   /add:
    post:
      description: aggiunge un astronauta
      operationId: AddAstronauti
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronauta'
        default:
          description: Errore
   
definitions:        
  Astronauta:
      required:
        - astroId
        - firstName
        - lastName
        - isInSpace
      properties:
          astroId:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          isInSpace:
            type: boolean